version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GitRuntimeAutomationAzurePdProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SIQA_GitRuntimeAutomationAzurePdProject
  gitUsername: siqagituser
  gitBranch: main
